### ISSUE TITLE
Blue Skies Dimension cannot change colors

### ISSUE THREAD

**Issue by Dr-WeiAL** [Ewan-Selkirk/Dimension-Viewer#2] opened 2023-06-17 00:31 UTC
I set it up this way, but in the end only twilightforest took effect
`modded_dimension_ids = ["twilightforest:twilight_forest DARK_PURPLE", "blue_skies:everbright DARK_BLUE", "blue_skies:everdawn GOLD"]`

**Comment by Ewan-Selkirk** [comment] 2023-06-17 02:22
Turns out I missed a character and any modid that had an underscore in it was seen as invalid...
The problem is fixed now, I'll try and upload a new version to CurseForge and Modrinth tomorrow.

Thanks for the report!

**Closed** 2023-06-17 02:22 UTC
